# Generated by Django 4.1.3 on 2022-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Масса блюда')),
                ('cost', models.IntegerField(verbose_name='Стоимость блюда')),
                ('photo', models.TextField(verbose_name='Ссылка на изображение')),
            ],
        ),
    ]
