# Generated by Django 4.1.3 on 2023-01-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salats',
            options={'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
    ]
