# Generated by Django 4.1.3 on 2022-11-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salats',
            options={'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
        migrations.AlterField(
            model_name='salats',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Ссылка на изображение'),
        ),
    ]
