# Generated by Django 4.1.3 on 2022-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_salats_options_alter_salats_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Объем напитка')),
                ('cost', models.IntegerField(verbose_name='Стоимость напитка')),
                ('photo', models.TextField(blank=True, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Напитки',
                'verbose_name_plural': 'Напиток',
            },
        ),
        migrations.CreateModel(
            name='HotDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Масса блюда')),
                ('cost', models.IntegerField(verbose_name='Стоимость блюда')),
                ('photo', models.TextField(blank=True, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Горячие блюда',
                'verbose_name_plural': 'Горячее блюдо',
            },
        ),
        migrations.CreateModel(
            name='SideDishesAndSoups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(verbose_name='Масса блюда')),
                ('cost', models.IntegerField(verbose_name='Стоимость блюда')),
                ('photo', models.TextField(blank=True, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Гарниры и супы',
                'verbose_name_plural': 'Гарнир или суп',
            },
        ),
    ]
