# Generated by Django 4.1.3 on 2022-11-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rentatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name': 'Ссылки на фото',
                'verbose_name_plural': 'Ссылка на фото',
            },
        ),
    ]
