# Generated by Django 4.1.3 on 2023-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photolinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinks',
            options={'ordering': ['title', 'weight', 'cost'], 'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='hotdishes',
            options={'ordering': ['title', 'weight', 'cost'], 'verbose_name': 'Горячее блюдо', 'verbose_name_plural': 'Горячие блюда'},
        ),
        migrations.AlterModelOptions(
            name='photolinks',
            options={'verbose_name': 'Ссылка на фото', 'verbose_name_plural': 'Ссылки на фото'},
        ),
        migrations.AlterModelOptions(
            name='rentatable',
            options={'ordering': ['client_name', 'clients_count', 'date', 'time'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='salats',
            options={'ordering': ['title', 'weight', 'cost'], 'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
        migrations.AlterModelOptions(
            name='sidedishesandsoups',
            options={'ordering': ['title', 'weight', 'cost'], 'verbose_name': 'Гарнир или суп', 'verbose_name_plural': 'Гарниры и супы'},
        ),
        migrations.AlterField(
            model_name='rentatable',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Номер телефона клиента'),
        ),
    ]
