# Generated by Django 4.1.3 on 2023-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_salats_options'),
        ('main', '0006_alter_drinks_options_alter_hotdishes_options_and_more'),
    ]

    operations = [
    ]
