# Generated by Django 4.1.3 on 2023-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20230114_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salats',
            options={'ordering': ['title', 'weight', 'cost'], 'verbose_name': 'Салат', 'verbose_name_plural': 'Салаты'},
        ),
    ]
