# Generated by Django 4.1.3 on 2023-01-15 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_drinks_title_en_drinks_title_ru_hotdishes_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='cost',
            field=models.IntegerField(verbose_name='The cost of the dish'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Link to the image'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='weight',
            field=models.IntegerField(verbose_name='Mass of the dish'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='cost',
            field=models.IntegerField(verbose_name='The cost of the dish'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Link to the image'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotdishes',
            name='weight',
            field=models.IntegerField(verbose_name='Mass of the dish'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='cost',
            field=models.IntegerField(verbose_name='The cost of the dish'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Link to the image'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='salats',
            name='weight',
            field=models.IntegerField(verbose_name='Mass of the dish'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='cost',
            field=models.IntegerField(verbose_name='The cost of the dish'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Link to the image'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sidedishesandsoups',
            name='weight',
            field=models.IntegerField(verbose_name='Mass of the dish'),
        ),
        migrations.CreateModel(
            name='HistoricalSideDishesAndSoups',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('weight', models.IntegerField(verbose_name='Mass of the dish')),
                ('cost', models.IntegerField(verbose_name='The cost of the dish')),
                ('photo', models.TextField(blank=True, verbose_name='Link to the image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Гарнир или суп',
                'verbose_name_plural': 'historical Гарниры и супы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalats',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('weight', models.IntegerField(verbose_name='Mass of the dish')),
                ('cost', models.IntegerField(verbose_name='The cost of the dish')),
                ('photo', models.TextField(blank=True, verbose_name='Link to the image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Салат',
                'verbose_name_plural': 'historical Салаты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRentATable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('clients_count', models.IntegerField(verbose_name='Количество гостей')),
                ('date', models.DateField(verbose_name='Дата прихода гостей')),
                ('time', models.TimeField(verbose_name='Время прихода гостей')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона клиента')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Бронирование',
                'verbose_name_plural': 'historical Бронирования',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHotDishes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('weight', models.IntegerField(verbose_name='Mass of the dish')),
                ('cost', models.IntegerField(verbose_name='The cost of the dish')),
                ('photo', models.TextField(blank=True, verbose_name='Link to the image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Горячее блюдо',
                'verbose_name_plural': 'historical Горячие блюда',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDrinks',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('weight', models.IntegerField(verbose_name='Mass of the dish')),
                ('cost', models.IntegerField(verbose_name='The cost of the dish')),
                ('photo', models.TextField(blank=True, verbose_name='Link to the image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Напиток',
                'verbose_name_plural': 'historical Напитки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
