# Generated by Django 4.1.3 on 2023-01-15 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_drinks_cost_alter_drinks_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhotdishes',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsalats',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsidedishesandsoups',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDrinks',
        ),
        migrations.DeleteModel(
            name='HistoricalHotDishes',
        ),
        migrations.DeleteModel(
            name='HistoricalSalats',
        ),
        migrations.DeleteModel(
            name='HistoricalSideDishesAndSoups',
        ),
    ]
